homepage = https://github.com/diodonfrost/exheres
summary = "diodonfrost's Exherbo packages"
description = "My personal Exherbo repository"
owner = diodonfrost <diodon.frost@diodonfrost.me>
status = third-party
